# Generated by Django 4.1.7 on 2023-05-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Email", models.CharField(max_length=100)),
                ("Mobile_No", models.IntegerField(default=" ")),
                ("Password", models.CharField(max_length=30)),
                ("Confirm_password", models.CharField(max_length=30)),
            ],
        ),
    ]
