# Generated by Django 4.1.7 on 2023-05-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Contact", "0002_login_alter_registration_mobile_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Total_Stock", models.CharField(max_length=10)),
                ("Total_Sales", models.CharField(max_length=10)),
                ("Profit", models.CharField(max_length=10)),
                ("Loss", models.CharField(max_length=10)),
                ("New_Order", models.TextField(max_length=100)),
            ],
        ),
    ]
