# Generated by Django 4.1.7 on 2023-05-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Contact", "0003_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Email", models.CharField(max_length=100)),
                ("Order", models.CharField(max_length=200)),
                ("Address", models.CharField(max_length=150)),
                ("Query", models.TextField()),
            ],
        ),
    ]
